# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  dockerize:
    name: Load sample express app
    runs-on: ubuntu-latest
    container: 
      image: radinreth/sample-express
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: check out
        uses: actions/checkout@v2
      - name: Running yarn install
        run: yarn install
      - name: Running yarn app
        run: yarn dev
